apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-backend
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: GRAFANA_ADMIN_USER
      metadataPolicy: None
      nullBytePolicy: Ignore
    secretKey: admin-user
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: GRAFANA_ADMIN_PASSWORD
      metadataPolicy: None
      nullBytePolicy: Ignore
    secretKey: admin-password
