apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-backend
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
  data:
    - remoteRef:
        key: GRAFANA_ADMIN_USER
      secretKey: admin-user
    - remoteRef:
        key: GRAFANA_ADMIN_PASSWORD
      secretKey: admin-password
