apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-backend
  target:
    name: operator-oauth # The name Tailscale Operator expects by default
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client_id: "{{ .client_id }}"
        client_secret: "{{ .client_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: TAILSCALE_OPERATOR_CLIENT_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: client_secret
      remoteRef:
        key: TAILSCALE_OPERATOR_CLIENT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
