apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vm-agent
  namespace: monitoring
spec:
  # Search for monitors in all namespaces
  selectAllByDefault: true
  
  # Remote write to our VMSingle instance
  remoteWrite:
    - url: "http://vmsingle-vm-shared.monitoring.svc:8429/api/v1/write"

  # Scrape intervals
  scrapeInterval: "30s"

  # Resource Management
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
