apiVersion: ENC[AES256_GCM,data:Yn8=,iv:WYPjjfkCbC1QPO8tPe7ryC7FY98MWh1YXYRmb/dq5p8=,tag:K4CpmLf00/iXDG7TNupVqw==,type:str]
kind: ENC[AES256_GCM,data:s7Rh4pAq,iv:wBGdGj7hzv0dRPpZg6w/mEFq1bLJ37bOqSy3kyySZd8=,tag:ZbT90VqqhqVB5Sw4XPIdoQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TV5joEcT70rxrWjKNU4z2g==,iv:dOpe7Zqkosp7HpI23U+trxUwkMgMlVRMh4r+vkBXk9E=,tag:wckmD65LNsa9kcTHbfer8A==,type:str]
    namespace: ENC[AES256_GCM,data:CXtXgE7v,iv:kM1MSGwc+ncYqL/p0pDmDUjTduRLIxsfDJp82eRTGfo=,tag:Iakv8ESeNJBUsleORvRwdg==,type:str]
stringData:
    hello: ENC[AES256_GCM,data:19Rv5Nc=,iv:1q6U9fm7F2eltIzLbldVdeKFagGmOr18I2Fb54qaY/Y=,tag:vMsEJjAZ9QYxdBFiNbOmqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTTExT3hDTWxuUmRrODZ6
            SEZ2M01naUNyU1I3a1NFTzBPQXBzaHhnUHg0CjBTbzgwY2Y2MGk3b3J2T2ViOXF5
            WWhkZmNpTUo5eTVIeU16UG9ZTkl5NDgKLS0tIFpLejFIeGczemd4b3VZeDBxcURy
            Vk9WS2hWdzZkbU9iOExjdFBNUGtubTAKPI+3+7q2pseoayXOmDdRW0SAWruH6rwh
            J6rab/801twkSTyyeWkN7Ll8URIzv4SS3pSfLQ9UoNVSnWb/EG69dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k875glhtpwxyqewspu0v02ln6etpk9a2jdnddvtxpwtanrha7e3syez3fa
    lastmodified: "2026-08-02T17:26:32Z"
    mac: ENC[AES256_GCM,data:CcKG3qMuXJQ9mf26mlixDzTc+jXn1R7yhGZLTI569JqLqZtpfjWZ49mv55ROJnh075wn31f87bawJCAIhAlre+w/1uSREoyBTwySLMHBTVpRZF1ZhtSnuu9mF0h+lcHPlvb/7ilNQXYfblbIklMjG/57RqpOCG1twUfrJ2Lrj2Y=,iv:3aDL79BgE7KbwDY1/z/v3aPNHulYNDCtsmvkSIo5Rz4=,tag:LLYKmVEPV7QATpIyCvdt2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
