apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster.yaml

# Server-Side Apply is mandatory for CNPG Cluster resources
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true
