apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-backend
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    infisical:
      hostAPI: "https://app.infisical.com"
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-auth      # Bootstrap secret created manually
            key: clientId
            namespace: external-secrets
          clientSecret:
            name: infisical-auth
            key: clientSecret
            namespace: external-secrets
      secretsScope:
        # Home > project: homelab > Project Settings -> General
        projectSlug: "homelab-y-vgb"
        environmentSlug: "prod"
        secretsPath: "/"
