replicaCount: 1

serviceAccount:
  create: true

# Webhook and CertController are essential for CRD validation and security
webhook:
  create: true
  replicaCount: 1

certController:
  create: true
  replicaCount: 1
