apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io
    targetRevision: 1.19.3
    helm:
      values: |
        ipam:
          mode: kubernetes
        kubeProxyReplacement: true
        securityContext:
          capabilities:
            ciliumAgent: ["CHOWN", "KILL", "NET_ADMIN", "NET_RAW", "IPC_LOCK", "SYS_ADMIN", "SYS_RESOURCE", "DAC_OVERRIDE", "FOWNER", "SETGID", "SETUID"]
            cleanCiliumState: ["NET_ADMIN", "SYS_ADMIN", "SYS_RESOURCE"]
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup
        k8sServiceHost: localhost
        k8sServicePort: 7445
        l2announcements:
          enabled: true
        k8sClientRateLimit:
          qps: 50
          burst: 100
        ingressController:
          enabled: true
          loadbalancerMode: shared
        gatewayAPI:
          enabled: true
          enableAlpn: true
          enableAppProtocol: true
          gatewayClass:
            create: "true"
        egressGateway:
          enabled: true
        bpf:
          masquerade: true
        nonIdempotentAnnotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: discovery.k8s.io
      kind: EndpointSlice
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: ""
      kind: ConfigMap
      name: hubble-ca-cert
      jsonPointers:
        - /data/ca.crt
    - group: ""
      kind: Secret
      name: hubble-relay-client-certs
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
    - group: ""
      kind: Secret
      name: hubble-server-certs
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
