apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  sources:
    # 1. Kaynak: Operator Helm Chart
    - repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.28.0
      chart: cloudnative-pg
    
    # 2. Kaynak: Yerel Cluster ve Storage Ayarları
    - repoURL: https://github.com/msavdert/homelab.git
      targetRevision: main
      path: apps/base/cloudnative-pg
      directory:
        include: "*.yaml"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
