apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz-k8s-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Deploy after signoz backend
spec:
  project: default
  sources:
    # 1. Source: SigNoz Official K8s-Infra Helm Chart
    - repoURL: https://charts.signoz.io
      targetRevision: 0.15.0
      chart: k8s-infra
      helm:
        valueFiles:
          - $homelab-ref/apps/base/k8s-infra/values.yaml
    
    # 2. Source: Reference for values.yaml
    - repoURL: https://github.com/msavdert/homelab.git
      targetRevision: main
      ref: homelab-ref
  
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
