apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 2.4.1
    chart: connect
    helm:
      values: |
        connect:
          create: true
          credentialsSecret: op-credentials
          # Use the 1password-credentials.json key from the secret
          credentialsName: 1password-credentials.json
        operator:
          create: true
          # The operator needs to know how to connect to the server
          token:
            secretName: op-credentials
            secretKey: token
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
