apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    # 1. Source: SigNoz Official Helm Chart
    - repoURL: https://charts.signoz.io
      targetRevision: 0.120.0
      chart: signoz
      helm:
        valueFiles:
          - $homelab/apps/base/signoz/values.yaml
    
    # 2. Source: Local Repository for values.yaml and manifests
    - repoURL: https://github.com/msavdert/homelab.git
      targetRevision: main
      path: apps/base/signoz
      ref: homelab
  
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
