apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    # 1. Source: SigNoz Official Helm Chart
    - repoURL: https://charts.signoz.io
      targetRevision: 0.121.0
      chart: signoz
      helm:
        valueFiles:
          - $homelab-ref/apps/base/signoz/values.yaml
    
    # 2. Source: Reference for values.yaml (Root access)
    - repoURL: https://github.com/msavdert/homelab.git
      targetRevision: main
      ref: homelab-ref

    # 3. Source: Local manifests (onepassword-item.yaml etc)
    - repoURL: https://github.com/msavdert/homelab.git
      targetRevision: main
      path: apps/base/signoz
      directory:
        exclude: "values.yaml"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/env/0/resourceFieldRef/divisor
        - /spec/template/spec/containers/0/env/1/resourceFieldRef/divisor
        - /spec/template/spec/containers/0/env/2/resourceFieldRef/divisor
        - /spec/template/spec/containers/0/env/3/resourceFieldRef/divisor
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates/0/apiVersion
        - /spec/volumeClaimTemplates/0/kind
