apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.76.0
    chart: victoria-metrics-k8s-stack
    helm:
      valuesObject:
        fullnameOverride: "vm"
        admissionWebhooks:
          enabled: true
          certManager:
            enabled: true
        vmsingle:
          enabled: true
          spec:
            retentionPeriod: "6"
            storage:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
        vmagent:
          enabled: true
          spec:
            scrapeInterval: "30s"
        vmalert:
          enabled: true
        grafana:
          enabled: true
          grafana.ini:
            database:
              wal: true
          podSecurityContext:
            fsGroup: 472
            runAsGroup: 472
            runAsUser: 472
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          # Readiness probe'u biraz esnetiyoruz
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          ingress:
            enabled: true
            ingressClassName: cilium
            hosts:
              - grafana.savdert.com
            annotations:
              ingress.cilium.io/loadbalancer-mode: shared
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
