apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-infrastructure
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/msavdert/homelab.git'
        revision: HEAD
        files:
          - path: "kubernetes/core/*/metadata.json"
  template:
    metadata:
      name: 'core-{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/msavdert/homelab.git'
        targetRevision: HEAD
        path: '{{path}}'
        kustomize: {}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
